[project]
name = "melly"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Batista Harahap", email = "batista@bango29.com" }
]
dependencies = [
    "fastapi>=0.111.0",
    "pydantic>=2.7.4",
    "typer>=0.12.3",
    "fastapi-jwt-auth3>=0.3.0",
    "beanie>=1.26.0",
    "pydantic-settings>=2.3.3",
    "pytz>=2024.1",
    "toml>=0.10.2",
    "ujson>=5.10.0",
    "httpx>=0.27.0",
    "uvicorn>=0.30.1",
    "python-slugify[unidecode]>=8.0.4",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.2.2",
    "pytest-asyncio>=0.23.7",
    "ruff>=0.4.10",
    "ruff-lsp>=0.0.53",
    "pytest-env>=1.1.3",
    "faker>=25.9.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/melly"]

[tool.ruff]
line-length = 120
exclude = [".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg", ".mypy_cache", ".nox", ".pants.d", ".pytype", ".ruff_cache", ".svn", ".tox", ".venv", "__pypackages__", "_build", "buck-out", "dist", "node_modules", "venv"]

[tool.rye.scripts]
docker-build = "bin/docker-build.sh"
test = "pytest -x -vv tests"

[tool.pytest_env]
BASE_URL = "http://localhost:8000"
FE_BASE_URL = "http://localhost:3000"
ENV = "test"
HOST = "127.0.0.1"
PORT = 8000
WEB_CONCURRENCY = 1
CORS_ORIGINS = "http://localhost:3000"
APPNAME = "api"
MONGO_URL = "mongodb://127.0.0.1:27017"
GROQ_API_KEY = "dummy"
OPENAI_API_KEY = "dummy"
OLLAMA_API_KEY = "dummy"
LLM_PROVIDER = "groq"
AUTH_ALGORITHM = "RS256"
B64_AUTH_PRIVATE_KEY = "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRElyRDhSUFJmVmE2MHAKTjJ5ajlRUXQyMjFPZms0b3RCRHJvZ1JDQ1I5ZTR1M2ZmNXZIRkx5S0NGczZiTXZ4aGFTRGdEMFRzWldhVWJldQovV2t2bVNBVFQ2YlVySmh6MUZqU3Nsak51QkNzaFZKNy9VU3R4VmVya1JPUHFVczRYblNpeHk2eCtHWkZvY0J3CmlLampZenNLSVhjWnJqcWZIbE82bndWakZSREEyL1pVUUoybmJpSnJGbDhsSmlBMjUxY2N4cnIrSllZWFhxcFAKdXR5Tk9pcXp6TnM4T3ZIVHlmTTFnZE5FZkNtdENRaUppeHJrNktCS3lRVE5Ma0JmUStuSE12T25nckJpL2RrLwo0eWpSenBSYW1RbUtFaVVFZTBUTHdCOEp5cUoyTm14L0dwb2xzOThkOGZNd2d5NVpSeUtack14b0lnQ1ZnR0MrCjNhWjk3eWZ4QWdNQkFBRUNnZ0VBSEFhNmRDemxKRUI2bWJRTTcwVXNCVCtOSDVaU1Vpcjc1ZnpsdlZkSzAxUzgKUmllcldQMlRhMi9KVmZxVjdUQnVEcE9kZEIrc05qWk5naG9RVTc1K0ZWUmRoM3huZWwzZzNlUmN0TGFOVlpyMQpMeTNySnAzV0piY0lWVnNlajB2WjNGWVhObkhyenJQTmphbjRkSEdLY0ZyR0tJY0YxdTFFWWw4TlFJNVRuYXViCmFxckNVaWlCdUNIb1dqUGppWnpJanFXMWJya25YamhPYWRkTTNUOTVJQXdwTGtXTzNQa1N3OGlTd0ZMMHRXcmEKemVSZGhIaWt2NHlCUGU5VENNM0I4VVVndUFHcG1zUXpOV3Zkd3MzYVJJQ0N4SVpaZmtWU2ZLaFZFajlLRElDTwpJRjNsTTNuYUtrRmZyRmxUa0hIbm50Ti8rWGpmZWxCYXdzSllVanBYZFFLQmdRRHdlUEs3NTE4RW5hek5Mai9ZCmxoUUZ6eThHQ2JPbG1mU1RLU29LekRLTmZaTElWb2RxaEdOalBFNHJpVXZLRkxvSW1wUTdrTThGVU5YaGdtNnIKRThIVmd6eHVDUEFlWFZSOWZISTZtTjJVKzlFMWNDVmlTa1ZocFRENkh0TTdLMWZLRFRVelJrTkI1NFNkalZlbApVRi8vSUhNSjZQOExYcTRlVXBEcDl3ZnpTd0tCZ1FEVm9XZE9VLzNrRmFPQ0lZUjZ4UHI1REllQ3RlUEt2MS9XCkNPWU1qclJCa2ljaDU0MzJZMWdqUXhZYTRlRFVLTUNvMFROYm1XY1N3eGgwVGtqYkV1N0dFRDhTNHc3Ung0VWMKZ2hxQVYzQTU5SStFK2Q1KytCeHFFdEZ3TWJDYkVhRFZZT3NYZFdGTUVsVUE1aThJcWVFUlJmU0RuNGRsVmlhNQpRcEVzbkU4UU13S0JnRDBnVVh0b05lUURmSkJ2YURWUytPWDlJMVBpbFhMTDdycVZwU1UzZ01Zc25Hb21iS2VyCjNXTzFTWjJSZWQxMVpWQ1lrb09Ock1JS0tVUDRsczhQNTU2eGpHUGdDOEY4TWVUd0JFMVczRVJwdW1WZUMzS3YKdEhFOHYzVms3b2JFM3J6eW5JcGJHdStldlR3YldLTWlDalRjOThFV0kvYXM2NCt6cHppQjNkaC9Bb0dBZkV4eApRMDN6aCtaZlFMUW4xUmNQd0NEZUo5dVZNcjZ2RUdZVkZIRmp5Rk0xbWJDVkZTc3dlVFByaExDd2xFRXgrQWZoCkRnYnZ4aWJsNzZZdEZlcXFLMndBaHdpOThxbFlkZ0h0VVllT3NPbnZKN3dMRFcxbmV3Q0FBL3VsZWxTRGRDUDAKSmE0U2NxU24rT0gxcytERUo3ekFUR1ZoN2tCMlA0elAwMWtQVjZrQ2dZRUE0dEQ0L01QdDVwS0NXUjEvQnFFaApSVExJczNJN3pUa0RhenBtRVdRRC9rQitVVmE2TGNSQzJkNC8rRGM4RktVTXl4VTBhemdLZmNXUDNpVFIyNUl4CmhVSjdJYloyL01Vd3FEaDdLQmpNcSswMXlXT1lTcUtuRnIzSkxjVGZQVndOL3VsaFl6NTRzdVk0MHpmVnNnQjcKOWxDRDNrdE5sNW9RTGlYd2pWY1JuWGs9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
B64_AUTH_PUBLIC_KEY = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5S3cvRVQwWDFXdXRLVGRzby9VRQpMZHR0VG41T0tMUVE2NklFUWdrZlh1THQzMytieHhTOGlnaGJPbXpMOFlXa2c0QTlFN0dWbWxHM3J2MXBMNWtnCkUwK20xS3lZYzlSWTBySll6YmdRcklWU2UvMUVyY1ZYcTVFVGo2bExPRjUwb3NjdXNmaG1SYUhBY0lpbzQyTTcKQ2lGM0dhNDZueDVUdXA4Rll4VVF3TnYyVkVDZHAyNGlheFpmSlNZZ051ZFhITWE2L2lXR0YxNnFUN3JjalRvcQpzOHpiUERyeDA4bnpOWUhUUkh3cHJRa0lpWXNhNU9pZ1Nza0V6UzVBWDBQcHh6THpwNEt3WXYzWlArTW8wYzZVCldwa0ppaElsQkh0RXk4QWZDY3FpZGpac2Z4cWFKYlBmSGZIek1JTXVXVWNpbWF6TWFDSUFsWUJndnQybWZlOG4KOFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
AUTH_TOKEN_EXPIRY = 3600
REFRESH_TOKEN_EXPIRY = 604800
SOCIAL_AUTH_EXPIRY_IN_SECONDS = 600
GOOGLE_CLIENT_ID = "dummy"
GOOGLE_CLIENT_SECRET = "dummy"
